application: naidom-api
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: naidom_api.APPLICATION

builtins:
- remote_api: on
- appstats: on

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0